name: Pages (branch previews)

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ main ]

permissions:
  contents: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create SPA fallback
        run: |
          cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: dist

  preview:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: dist

      - name: Publish PR preview to gh-pages/pr-<number>/
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
          destination_dir: pr-${{ github.event.pull_request.number }}
          keep_files: true

      - name: Comment preview URL on PR
        env:
          GH_TOKEN: ${{ github.token }}
          PREVIEW_URL: https://irontrip.github.io/landing/pr-${{ github.event.pull_request.number }}/
        run: |
          set -euo pipefail
          pr='${{ github.event.pull_request.number }}'
          payload=$(jq -nc --arg body "🚀 Preview deployed: ${PREVIEW_URL}" '{body:$body}')
          curl -sfSL -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "$payload" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${pr}/comments"

  production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: dist

      - name: Publish production to gh-pages root
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
