name: Pages (branch previews)

on:
  pull_request:
    branches: [ dev ]
  push:
    branches:
      - main
      - dev
      - fix/**

permissions:
  contents: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Provide Vite build-time public key for Web3Forms from repo variables
      VITE_WEB3FORMS_ACCESS_KEY: ${{ vars.VITE_WEB3FORMS_ACCESS_KEY }}
      # Accept either the old var name or your new one
      VITE_RECAPTCHA_SITE_KEY: ${{ vars.VITE_RECAPTCHA_SITE_KEY }}
      RECAPTCHA_PUBLIC_KEY: ${{ vars.RECAPTCHA_PUBLIC_KEY }}
      VITE_CONTACT_ENDPOINT: ${{ vars.VITE_CONTACT_ENDPOINT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Vite env file (.env.production)
        run: |
          echo "VITE_WEB3FORMS_ACCESS_KEY=${{ vars.VITE_WEB3FORMS_ACCESS_KEY }}" >> .env.production
          # Prefer VITE_RECAPTCHA_SITE_KEY if set; otherwise fallback to RECAPTCHA_PUBLIC_KEY
          echo "VITE_RECAPTCHA_SITE_KEY=${VITE_RECAPTCHA_SITE_KEY:-$RECAPTCHA_PUBLIC_KEY}" >> .env.production
          echo "VITE_CONTACT_ENDPOINT=${{ vars.VITE_CONTACT_ENDPOINT }}" >> .env.production

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create SPA fallback
        run: |
          cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: dist

  preview:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: dist

      - name: Publish PR preview to gh-pages/pr-<number>/
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
          destination_dir: pr-${{ github.event.pull_request.number }}
          keep_files: true

      - name: Announce preview URL in summary
        run: |
          echo "Preview URL: https://irontrip.github.io/landing/pr-${{ github.event.pull_request.number }}/" >> "$GITHUB_STEP_SUMMARY"

      - name: Comment preview URL on PR (non-fatal)
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
          PREVIEW_URL: https://irontrip.github.io/landing/pr-${{ github.event.pull_request.number }}/
        run: |
          pr='${{ github.event.pull_request.number }}'
          gh api repos/${{ github.repository }}/issues/${pr}/comments -f body="🚀 Preview deployed: ${PREVIEW_URL}"

  preview_branch:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/fix/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: dist

      - name: Compute branch slug
        id: slug
        run: |
          slug="${GITHUB_REF_NAME//\//-}" # replace slashes with dashes for folder name
          echo "slug=$slug" >> "$GITHUB_OUTPUT"

      - name: Publish branch preview to gh-pages/branches/<slug>/
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
          destination_dir: branches/${{ steps.slug.outputs.slug }}
          keep_files: true

      - name: Announce preview URL in summary
        run: |
          echo "Preview URL: https://irontrip.github.io/landing/branches/${{ steps.slug.outputs.slug }}/" >> "$GITHUB_STEP_SUMMARY"

  production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: dist

      - name: Publish production to gh-pages root
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages

  dev:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: dist

      - name: Publish current dev to gh-pages/dev
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
          destination_dir: dev
          keep_files: true
